### ISSUE TITLE
Modifica script server di produzione

### ISSUE THREAD

**Issue by ag7** [develersrl/app-pranzi#2]
Attualmente l'app consente di selezionare il giorno in cui segnare il pranzo.
Il problema è che, qualsiasi giorno l'utente scelga, viene sempre sovrascritto il pranzo del giorno corrente.

**Comment by ag7** [comment]
Il problema è che il Google App Script di produzione non è aggiornato e non contiene in particolare la funzionalità "scrivi nei giorni passati".

**Comment by ag7** [comment]
Ho aggiornato il backend (1b9003600908be21f25a6b7be36993c29c7af927) e adesso la scrittura dei pranzi nei giorni passati dovrebbe funzionare correttamente. Non è necessario alcun aggiornamento dell'app perchè la modifica ha riguardato solo il backend.

**Comment by giuseongit** [comment]
Ma scusa, ha senso mettere qui lo script che usiamo?
Il repo è pubblico e c'è il riferimento allo spreadsheet che usiamo per i pranzi!

**Comment by ag7** [comment]
Ho messo nel repo lo script che punta allo spreadsheet di sviluppo, non di produzione.
